server:
  port: 20999
clients:
  github-service:
    base-url: https://api.github.com
    repos: ${OWNED_GITHUB_REPOS}
    connect-timeout: 3s
    read-timeout: 10s
    access-token: ${GITHUB_ACCESS_TOKEN}
    get-repositories-path: "/user/repos"
    page-size: 100
spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show-sql: true
        generate_statistics: true
        order_updates: true
        jdbc:
          batch_size: 100
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        stat: DEBUG
        orm:
          results: TRACE
